/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTeamRouteImport } from './routes/_site.team'
import { Route as SiteResultsRouteImport } from './routes/_site.results'
import { Route as SiteResourcesRouteImport } from './routes/_site.resources'
import { Route as SitePressRouteImport } from './routes/_site.press'
import { Route as SitePartnershipsRouteImport } from './routes/_site.partnerships'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTeamRoute = SiteTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResultsRoute = SiteResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResourcesRoute = SiteResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SiteRoute,
} as any)
const SitePressRoute = SitePressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnershipsRoute = SitePartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/faq': typeof SiteFaqRoute
  '/partnerships': typeof SitePartnershipsRoute
  '/press': typeof SitePressRoute
  '/resources': typeof SiteResourcesRoute
  '/results': typeof SiteResultsRoute
  '/team': typeof SiteTeamRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/faq': typeof SiteFaqRoute
  '/partnerships': typeof SitePartnershipsRoute
  '/press': typeof SitePressRoute
  '/resources': typeof SiteResourcesRoute
  '/results': typeof SiteResultsRoute
  '/team': typeof SiteTeamRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/partnerships': typeof SitePartnershipsRoute
  '/_site/press': typeof SitePressRoute
  '/_site/resources': typeof SiteResourcesRoute
  '/_site/results': typeof SiteResultsRoute
  '/_site/team': typeof SiteTeamRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/partnerships'
    | '/press'
    | '/resources'
    | '/results'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/faq'
    | '/partnerships'
    | '/press'
    | '/resources'
    | '/results'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/faq'
    | '/_site/partnerships'
    | '/_site/press'
    | '/_site/resources'
    | '/_site/results'
    | '/_site/team'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/team': {
      id: '/_site/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof SiteTeamRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/results': {
      id: '/_site/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof SiteResultsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/resources': {
      id: '/_site/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof SiteResourcesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/press': {
      id: '/_site/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof SitePressRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partnerships': {
      id: '/_site/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof SitePartnershipsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePartnershipsRoute: typeof SitePartnershipsRoute
  SitePressRoute: typeof SitePressRoute
  SiteResourcesRoute: typeof SiteResourcesRoute
  SiteResultsRoute: typeof SiteResultsRoute
  SiteTeamRoute: typeof SiteTeamRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePartnershipsRoute: SitePartnershipsRoute,
  SitePressRoute: SitePressRoute,
  SiteResourcesRoute: SiteResourcesRoute,
  SiteResultsRoute: SiteResultsRoute,
  SiteTeamRoute: SiteTeamRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
