/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteResultsRouteImport } from './routes/_site.results'
import { Route as SitePartnershipsRouteImport } from './routes/_site.partnerships'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResultsRoute = SiteResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SiteRoute,
} as any)
const SitePartnershipsRoute = SitePartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/faq': typeof SiteFaqRoute
  '/partnerships': typeof SitePartnershipsRoute
  '/results': typeof SiteResultsRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/faq': typeof SiteFaqRoute
  '/partnerships': typeof SitePartnershipsRoute
  '/results': typeof SiteResultsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/partnerships': typeof SitePartnershipsRoute
  '/_site/results': typeof SiteResultsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/faq' | '/partnerships' | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/faq' | '/partnerships' | '/results' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/faq'
    | '/_site/partnerships'
    | '/_site/results'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/results': {
      id: '/_site/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof SiteResultsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/partnerships': {
      id: '/_site/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof SitePartnershipsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SitePartnershipsRoute: typeof SitePartnershipsRoute
  SiteResultsRoute: typeof SiteResultsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteFaqRoute: SiteFaqRoute,
  SitePartnershipsRoute: SitePartnershipsRoute,
  SiteResultsRoute: SiteResultsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
